[package]
name = "linear_regression_model"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.16.0", features = ["wgpu", "train", "ndarray"] }
burn-ndarray = "0.16.0"
rand = "0.9.0"
rgb = "0.8.50"
textplots = "0.8.7"

